name: API Privacy Test
on:
  push:
    branches: [ "main" ]
  # schedule:
  #    - cron: '*/5 * * * *'
 

jobs:
  build:
    runs-on: ubuntu-latest
   # runs-on: self-hosted
    steps:
      - name: PerfAI APIPrivacy Test
        uses: PerfAI-Inc/perfai-api-privacy@v0.0.1
        with:
           perfai-username: afrose@perfai.ai
           perfai-password: Tester@786
           perfai-api-id: "670962797223ce88cd6efb5d"
           perfai-api-name: "ActionL"
           perfai-wait-for-completion: "true"
           perfai-fail-on-new-leaks: "false"
   ### Email Alert Notifcation ###
      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v3.9.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "ðŸš¨ Build Failure: ${{ github.repository }} #${{ github.run_number }} ðŸš¨"
          body: |
             Hi,
             Unfortunately, the build for the project **${{ github.repository }}** has failed. Below are the details:
             **Build Information:**
               - Repository:  ${{ github.repository }}
               - Branch:  ${{ github.ref_name }}
               - Commit SHA:  ${{ github.sha }}
               - Commit Message:  ${{ github.event.head_commit.message }}
             **Failure Summary:*
               - Please review the logs for more details: [View Logs] 
                   ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: fatima@perfai.ai
          from: PerfAI       
